# Generated by Django 5.2.4 on 2025-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
