# Generated by Django 5.2.3 on 2025-07-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('phoneNumber', models.CharField(max_length=25)),
            ],
        ),
    ]
